http://localhost:3000/records/events-03/csv?filters=own
http://localhost:3000/transactions/events-03/csv?filters=own
http://localhost:3000/pianostudents/students/csv
http://localhost:3000/transactions/events-02/csv?filters=own
http://localhost:3000/transactions/events-01/csv?filters=own
http://localhost:3000/transactions/events/csv
